/// to do llevarme todo esto a back
export const cabinsData = [
  {
    id: '1',
    name: 'Cabaña 1-Zeus',
    deity: 'Zeus',
    cabinNumber: 1,
    imageUrl: 'https://images.unsplash.com/photo-1576613775061-75e52d6e6b0e?q=80&w=1112&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    deityDescription:
      'Es la cabaña número 1, la más grande y voluminosa de todas las cabañas del campamento, aunque no está amueblada. Construida de mármol blanco con grandes columnas y puertas de bronce que parecen rayos según el ángulo de visión. Contiene una estatua de seis metros de Zeus con escudo y rayo.',
    location: 'Al inicio del área central del círculo de cabañas, cabaña más grande e impresionante',
    camperAttributes: [
      { name: 'Liderazgo', description: 'Los hijos de Zeus son líderes naturales con fuerte voluntad.' },
      { name: 'Poderes del aire', description: 'Pueden manipular corrientes de aire y controlar el clima.' },
      { name: 'Manipulación de electricidad', description: 'Capaces de generar y controlar rayos.' },
      { name: 'Fuerza de voluntad', description: 'Resilientes y determinados frente a desafíos.' },
    ],
    activities: [
      'Entrenamiento en liderazgo',
      'Práctica de manipulación del clima',
      'Entrenamiento de vuelo avanzado',
      'Talleres de estrategia y tácticas',
      'Relaciones diplomáticas con otras cabañas',
    ],
    assignedUsers: ['1'],
  },
  {
    id: '2',
    name: 'Cabaña 2- Hera',
    deity: 'Hera',
    cabinNumber: 2,
    imageUrl: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    deityDescription:
      'Cabaña de mármol decorada con columnas blancas, guirnaldas de flores y granadas. Contiene una estatua gigante de Hera con un pozo de fuego. Es honoraria ya que Hera no tiene hijos semidioses.',
    location: 'Junto a la cabaña de Zeus, a su derecha',
    camperAttributes: [
      { name: 'Elegancia', description: 'Representa la gracia y majestuosidad de Hera.' },
      { name: 'Sabiduría matrimonial', description: 'Conocimiento sobre relaciones y vínculos familiares.' },
    ],
    activities: ['Observación de ceremonias', 'Estudio de mitología familiar'],
    assignedUsers: ['2'],
  },
  {
    id: '3',
    name: 'Cabaña 3-Poseidón',
    deity: 'Poseidón',
    cabinNumber: 3,
    imageUrl: 'https://images.unsplash.com/photo-1523659945955-fe95eb9bc70b?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    deityDescription:
      'Cabaña baja y larga con todas las ventanas mirando al mar. Muros de piedra gris con coral y conchas. Huele a salobre y tiene literas con sábanas de seda. Habitada por Percy Jackson y su hermano Tyson.',
    location: 'A la izquierda de la cabaña de Zeus, cerca del lago',
    camperAttributes: [
      { name: 'Poderes acuáticos', description: 'Respirar bajo el agua y controlar el agua.' },
      { name: 'Generación de terremotos', description: 'Capacidad de causar temblores leves.' },
      { name: 'Afinidad con caballos', description: 'Conexión natural con caballos y criaturas marinas.' },
      { name: 'Navegación', description: 'Excelente sentido de orientación.' },
    ],
    activities: [
      'Entrenamiento de combate acuático',
      'Estudios de biología marina',
      'Navegación y manejo de embarcaciones',
      'Práctica de manipulación de agua',
      'Cuidado de caballos',
    ],
    assignedUsers: ['3'],
  },
  {
    id: '4',
    name: 'Cabaña 4-Deméter',
    deity: 'Deméter',
    cabinNumber: 4,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1667423049497-291580083466?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Z2FyZGVufGVufDB8fDB8fHww',
    deityDescription:
      'Cabaña marrón claro con techo de césped y paredes cubiertas de plantas y flores. Porche con flores silvestres y rosas. Capitán Katie Gardner.',
    location: 'Área este del círculo de cabañas, cerca del huerto',
    camperAttributes: [
      { name: 'Conexión con la tierra', description: 'Capacidad de cultivar y cuidar plantas.' },
      { name: 'Habilidades agrícolas', description: 'Experiencia en cultivo y cosecha.' },
    ],
    activities: ['Cultivo de vegetales', 'Estudio de botánica', 'Cuidado de jardines y huertos'],
    assignedUsers: ['4'],
  },
  {
    id: '5',
    name: 'Cabaña 5-Ares',
    deity: 'Ares',
    cabinNumber: 5,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1716845059757-8cad6ef73b39?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    deityDescription:
      'Cabaña roja brillante con alambre de púas en el techo y cabeza de jabalí disecada en la puerta. Interior lleno de campistas. Capitán Clarisse La Rue.',
    location: 'Área este del círculo de cabañas, cerca del campo de batalla',
    camperAttributes: [
      { name: 'Combate', description: 'Habilidad en batalla y estrategia militar.' },
      { name: 'Valentía', description: 'No temen enfrentarse a desafíos peligrosos.' },
    ],
    activities: ['Entrenamiento de combate', 'Prácticas de estrategia militar'],
    assignedUsers: ['5'],
  },
  {
    id: '6',
    name: 'Cabaña 6-Atenea',
    deity: 'Atenea',
    cabinNumber: 6,
    imageUrl: 'https://images.unsplash.com/photo-1544822688-c5f41d2c1972?q=80&w=1119&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    deityDescription:
      'Cabaña azul y dorada con búho tallado sobre la puerta. Contiene taller y biblioteca con estanterías y mesas para estudiar. Capitán Annabeth Chase.',
    location: 'Área este del círculo de cabañas',
    camperAttributes: [
      { name: 'Sabiduría', description: 'Conocimiento y estrategia avanzada.' },
      { name: 'Habilidad intelectual', description: 'Capacidad de resolver problemas complejos.' },
    ],
    activities: ['Estudio y lectura', 'Clases de estrategia', 'Taller de invenciones'],
    assignedUsers: ['6'],
  },
  {
    id: '7',
    name: 'Cabaña 7-Apolo',
    deity: 'Apolo',
    cabinNumber: 7,
    imageUrl: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    deityDescription:
      'Cabaña que brilla con la luz del sol, pareciendo hecha de oro. Capitanes: Lee Fletcher, Michael Yew, Will Solace.',
    location: 'Área este del círculo de cabañas',
    camperAttributes: [
      { name: 'Artes', description: 'Habilidad en música, poesía y creatividad.' },
      { name: 'Curación', description: 'Capacidad de curar con rayos de luz.' },
    ],
    activities: ['Clases de música y poesía', 'Prácticas de curación'],
    assignedUsers: ['7'],
  },
  {
    id: '8',
    name: 'Cabaña 8-Artemisa',
    deity: 'Artemisa',
    cabinNumber: 8,
    imageUrl: 'https://images.unsplash.com/photo-1677229524888-6a0faba396c3?q=80&w=1768&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3DURL_ARTEMISA',
    deityDescription:
      'Edificio plateado que brilla por la noche. Decorado con símbolos de animales salvajes, especialmente ciervos. Solo ocupada por las cazadoras de Artemisa.',
    location: 'Área este del círculo de cabañas, cerca del bosque',
    camperAttributes: [
      { name: 'Caza', description: 'Habilidad en rastreo y caza de animales.' },
      { name: 'Sigilo', description: 'Capacidad de moverse sin ser detectado.' },
    ],
    activities: ['Entrenamiento de caza', 'Clases de supervivencia'],
    assignedUsers: ['8'],
  },
  {
    id: '9',
    name: 'Cabaña 9-Hefesto',
    deity: 'Hefesto',
    cabinNumber: 9,
    imageUrl: 'https://images.unsplash.com/photo-1528918652533-dfdb3f368093?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    deityDescription:
      'Cabaña con paredes de hierro y puertas metálicas. Interior desordenado con herramientas, armas y chatarra. Capitán Leo Valdez.',
    location: 'Área de taller',
    camperAttributes: [
      { name: 'Herramientas', description: 'Habilidad para construir y reparar objetos.' },
      { name: 'Ingeniería', description: 'Capacidad de crear inventos mecánicos.' },
    ],
    activities: ['Trabajo en taller', 'Creación de inventos'],
    assignedUsers: ['9'],
  },
  {
    id: '10',
    name: 'Cabaña 10-Afrodita',
    deity: 'Afrodita',
    cabinNumber: 10,
    imageUrl: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cm9tYW5jZXxlbnwwfHwwfHx8MA%3D%3D',
    deityDescription:
      'Cabaña rosa con cortinas azules y verdes. Literas decoradas con fotos de estrellas de cine. Capitán actual Piper McLean.',
    location: 'Área este del círculo de cabañas',
    camperAttributes: [
      { name: 'Belleza', description: 'Habilidad para atraer y encantar.' },
      { name: 'Amor', description: 'Capacidad de influir en sentimientos y relaciones.' },
    ],
    activities: ['Clases de moda', 'Eventos de socialización'],
    assignedUsers: ['10'],
  },
  {
    id: '11',
    name: 'Cabaña 11-Hermes',
    deity: 'Hermes',
    cabinNumber: 11,
    imageUrl: 'https://images.unsplash.com/photo-1591454843640-8b81f8dbc382?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FkdWNlb3xlbnwwfHwwfHx8MA%3D%3D',
    deityDescription:
      'Cabaña que más se asemeja a una típica cabaña de campamento. Umbral gastado y pintura desconchada. Acepta semidioses no reconocidos. Capitanes actuales: Travis y Connor Stoll.',
    location: 'Área este del círculo de cabañas, cerca del camino de entrada',
    camperAttributes: [
      { name: 'Agilidad', description: 'Habilidad para moverse rápido y con destreza.' },
      { name: 'Ingenio', description: 'Gran creatividad y astucia.' },
    ],
    activities: ['Masterclass de bromas', 'Clases de sigilo y escape'],
    assignedUsers: ['11'],
  },
  {
    id: '12',
    name: 'Cabaña 12-Dioniso',
    deity: 'Dioniso',
    cabinNumber: 12,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1677354136477-6c9f75f65038?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8bWFzY2FyYWRlfGVufDB8fDB8fHww',
    deityDescription:
      'Cabaña decorada con racimos de uva. Número de habitantes pequeño. Capitán: Pólux.',
    location: 'Área oeste del círculo de cabañas',
    camperAttributes: [
      { name: 'Fiesta', description: 'Habilidad para organizar celebraciones.' },
      { name: 'Creatividad', description: 'Capacidad de disfrutar y crear diversión.' },
    ],
    activities: ['Clases de vino y licor', 'Celebraciones y eventos'],
    assignedUsers: ['12'],
  },
  {
    id: '13',
    name: 'Cabaña 13-Hades',
    deity: 'Hades',
    cabinNumber: 13,
    imageUrl: 'https://images.unsplash.com/photo-1603516863860-7d5c93a83fe8?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    deityDescription:
      'Cabaña de obsidiana con cráneo sobre la puerta y antorchas de fuego griego encendidas las 24 horas. Capitán: Nico di Angelo.',
    location: 'Área oeste del círculo de cabañas, sigue la flora muerta y el suelo árido para encontrarla',
    camperAttributes: [
      { name: 'Control de muertos', description: 'Habilidad para convocar y comunicarse con los muertos.' },
      { name: 'Misterio', description: 'Gran conocimiento de secretos y sombras.' },
    ],
    activities: ['Prácticas de necromancia', 'Mantenimiento del inframundo'],
    assignedUsers: ['13'],
  },
  {
    id: '14',
    name: 'Cabaña 14-Iris',
    deity: 'Iris',
    cabinNumber: 14,
    imageUrl: 'https://images.unsplash.com/photo-1579313205978-cd787f9bfb4a?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    deityDescription:
      'Cabaña pintada con los colores del arcoíris, con estatua gigante de Iris en su interior. Capitán: Butch Walker.',
    location: 'Área oeste del círculo de cabañas',
    camperAttributes: [
      { name: 'Comunicación', description: 'Capacidad de transmitir mensajes y señales.' },
      { name: 'Rapidez', description: 'Habilidad para moverse velozmente.' },
    ],
    activities: ['Transporte de mensajes', 'Fabricación de Atrapasoles'],
    assignedUsers: ['14'],
  },
  {
    id: '15',
    name: 'Cabaña 15-Hipnos',
    deity: 'Hipnos',
    cabinNumber: 15,
    imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?q=80&w=1160&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    deityDescription:
      'Cabaña de barro con techos en punta y chimenea con fuego constante. Música de violín suave y aroma a ropa limpia. Capitán: Clovis.',
    location: 'Área oeste del círculo de cabañas',
    camperAttributes: [
      { name: 'Sueño', description: 'Control sobre el sueño y el descanso.' },
      { name: 'Tranquilidad', description: 'Capacidad de inducir calma y paz.' },
    ],
    activities: ['Meditación', 'Prácticas de sueño reparador', 'Siesta Grupal'],
    assignedUsers: ['15'],
  },
  {
    id: '16',
    name: 'Cabaña 16-Némesis',
    deity: 'Némesis',
    cabinNumber: 16,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1668058723804-d7dcd1ffa4c9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8ZXF1aWxpYnJpb3xlbnwwfHwwfHx8MA%3D%3D',
    deityDescription:
        'Cabaña con una rueda rota colgando en la puerta, similar a un Pac-Man. Número de ocupantes desconocido. La cabaña fue construida después de los acontecimientos de El último héroe del Olimpo.',
      location: 'Área oeste del círculo de cabañas',
      camperAttributes: [
        { name: 'Justicia', description: 'Capacidad de equilibrar y medir acciones.' },
        { name: 'Competitividad', description: 'Los hijos buscan superar retos constantemente.' },
      ],
      activities: ['Prácticas de estrategia', 'Competencias y desafíos'],
      assignedUsers: ['16'],
    },
    {
      id: '17',
      name: 'Cabaña 17-Niké',
      deity: 'Niké',
      cabinNumber: 17,
      imageUrl: 'https://images.unsplash.com/photo-1705049769631-d3ffc84c7e81?q=80&w=627&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      deityDescription:
        'No se conocen ocupantes. Los hijos de Niké son muy competitivos y nunca rechazan un reto. Sus capitanas son Holly Victor y Laurel Victor.',
      location: 'Área de oeste del círculo de cabañas',
      camperAttributes: [
        { name: 'Competitividad', description: 'Viven para los concursos y nunca se conforman.' },
        { name: 'Determinación', description: 'Perseveran para ganar en todo momento.' },
      ],
      activities: ['Competiciones deportivas', 'Desafíos de habilidad'],
      assignedUsers: ['17'],
    },
    {
      id: '18',
      name: 'Cabaña 18-Hebe',
      deity: 'Hebe',
      cabinNumber: 18,
      imageUrl: 'https://images.unsplash.com/photo-1499540633125-484965b60031?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      deityDescription:
        'Cabaña de mármol con apariencia regular. Frente a ella hay una fuente destinada a reproducir la fuente de la juventud de Hebe. El interior tiene literas a los lados, chimenea de mármol y estatua de Hebe en el medio.',
      location: 'Área oeste del círculo de cabañas',
      camperAttributes: [
        { name: 'Vitalidad', description: 'Promueve la juventud y el bienestar.' },
        { name: 'Hospitalidad', description: 'Capacidad de cuidar y atender a los campistas.' },
      ],
      activities: ['Mantenimiento de la fuente', 'Cuidado de campistas jóvenes'],
      assignedUsers: ['18'],
    },
    {
      id: '19',
      name: 'Cabaña 19-Tique',
      deity: 'Tique',
      cabinNumber: 19,
      imageUrl: 'https://images.unsplash.com/photo-1605142859862-978be7eba909?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YXphcnxlbnwwfHwwfHx8MA%3D%3D',
      deityDescription:
        'Cabaña que parece un mini casino de Las Vegas. No se conocen ni mencionan ocupantes.',
      location: 'Área oeste del circulo de cabañas',
      camperAttributes: [
        { name: 'Suerte', description: 'Atrae o maneja la fortuna de manera especial.' },
        { name: 'Riesgo', description: 'Capacidad de tomar decisiones arriesgadas.' },
      ],
      activities: ['Juegos de azar', 'Prácticas de estrategia y suerte'],
      assignedUsers: ['19'],
    },
    {
      id: '20',
      name: 'Cabaña 20-Hécate',
      deity: 'Hécate',
      cabinNumber: 20,
      imageUrl: 'https://plus.unsplash.com/premium_photo-1693007962882-0671e3867ed6?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      deityDescription:
        'Cabaña hecha de piedra mágica. Si una piedra cae, explota o convierte todo a su alrededor en árboles hasta una milla y media. Capitán Lou Ellen.',
      location: 'Area oeste del circulo de cabañas, ultima cabaña antes del bosque ',
      camperAttributes: [
        { name: 'Magia', description: 'Afinidad natural con las artes mágicas y místicas.' },
        { name: 'Misterio', description: 'Habilidad para lo oculto y lo desconocido.' },
      ],
      activities: ['Clases de magia', 'Manipulación de hechizos', 'Prácticas de arte místico'],
      assignedUsers: ['20'],
    },
];